/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/MDrew/MDrew.gltf -t -r public 
*/

// @ts-ignore
import * as THREE from 'react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    Circle: THREE.Mesh
    Cube011: THREE.Mesh
    Cylinder007: THREE.Mesh
    Cube012: THREE.Mesh
    Cylinder008: THREE.Mesh
    Cylinder009: THREE.Mesh
    Body1001_1: THREE.Mesh
    Body1001_2: THREE.Mesh
    Body1001_3: THREE.Mesh
    Body1001_4: THREE.Mesh
    Body1001_5: THREE.Mesh
    Body1001_6: THREE.Mesh
    Body1001_7: THREE.Mesh
    Body1001_8: THREE.Mesh
    Body1001_9: THREE.Mesh
    Body1001_10: THREE.Mesh
    Body1001_11: THREE.Mesh
    Body1001_12: THREE.Mesh
    Body1001_13: THREE.Mesh
    Body1002: THREE.Mesh
    Body1002_1: THREE.Mesh
    Body1002_2: THREE.Mesh
    Body1002_3: THREE.Mesh
    Body1002_4: THREE.Mesh
    Body1002_5: THREE.Mesh
    Gear001: THREE.Mesh
    Gear004: THREE.Mesh
    Body1018: THREE.Mesh
    Body1018_1: THREE.Mesh
    Body1018_2: THREE.Mesh
    Body1018_3: THREE.Mesh
    Body1018_4: THREE.Mesh
    Body1018_5: THREE.Mesh
    Body1018_6: THREE.Mesh
    Cylinder006: THREE.Mesh
    Circle001: THREE.Mesh
    Circle002: THREE.Mesh
    Circle003: THREE.Mesh
    Circle004: THREE.Mesh
    Body2005: THREE.Mesh
    Body2005_1: THREE.Mesh
    Body2005_2: THREE.Mesh
    Body2005_3: THREE.Mesh
    Body2005_4: THREE.Mesh
    Body2005_5: THREE.Mesh
    Body2005_6: THREE.Mesh
    Body2005_7: THREE.Mesh
    Body2005_8: THREE.Mesh
    Body2005_9: THREE.Mesh
    Body2005_10: THREE.Mesh
    Body2005_11: THREE.Mesh
    Body2005_12: THREE.Mesh
    Body2005_13: THREE.Mesh
    Body2005_14: THREE.Mesh
    Body1416_1: THREE.Mesh
    Body1416_2: THREE.Mesh
    Body1416_3: THREE.Mesh
    Body1416_4: THREE.Mesh
    Body1416_5: THREE.Mesh
    Body1416_6: THREE.Mesh
    Body1416_7: THREE.Mesh
    Body1416_8: THREE.Mesh
    Body1416_9: THREE.Mesh
    Body1416_10: THREE.Mesh
    Body1416_11: THREE.Mesh
    Body1416_12: THREE.Mesh
    Body1416_13: THREE.Mesh
    Body1416_14: THREE.Mesh
    Body1416_15: THREE.Mesh
    Body1416_16: THREE.Mesh
    Body1416_17: THREE.Mesh
    Body1416_18: THREE.Mesh
    Body1416_19: THREE.Mesh
    Body1416_20: THREE.Mesh
    Body1416_21: THREE.Mesh
    Body1416_22: THREE.Mesh
    Body1416_23: THREE.Mesh
    Body1416_24: THREE.Mesh
    Body1416_25: THREE.Mesh
    Body1416_26: THREE.Mesh
    Body1416_27: THREE.Mesh
    Body1416_28: THREE.Mesh
    Body1416_29: THREE.Mesh
    Cube: THREE.Mesh
    Plane: THREE.Mesh
    Text: THREE.Mesh
    Text001: THREE.Mesh
    Text002: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Cube005: THREE.Mesh
    Limelight_Vision_CAD: THREE.Mesh
    Robot_Signal_Light_RSL_v1: THREE.Mesh
    Cube006: THREE.Mesh
    Cube007: THREE.Mesh
    Cylinder002: THREE.Mesh
    Limelight_Vision_CAD001: THREE.Mesh
    Cube008: THREE.Mesh
    Cube009: THREE.Mesh
    Text003: THREE.Mesh
    Cube010: THREE.Mesh
    Cylinder001: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder004: THREE.Mesh
    Cylinder005: THREE.Mesh
    Body1: THREE.Mesh
    Body1_1: THREE.Mesh
    Body1_2: THREE.Mesh
    Body1_3: THREE.Mesh
    Body1_4: THREE.Mesh
    Body1_5: THREE.Mesh
    Body1_6: THREE.Mesh
    Body1_7: THREE.Mesh
    Body1_8: THREE.Mesh
    Body1_9: THREE.Mesh
    Body1_10: THREE.Mesh
    Body1_11: THREE.Mesh
    Body1_12: THREE.Mesh
    Body1004: THREE.Mesh
    Body1004_1: THREE.Mesh
    Body1004_2: THREE.Mesh
    Body1004_3: THREE.Mesh
    Body1004_4: THREE.Mesh
    Body1004_5: THREE.Mesh
    Body1004_6: THREE.Mesh
    Body1004_7: THREE.Mesh
    Body1004_8: THREE.Mesh
    Body1004_9: THREE.Mesh
    Body1004_10: THREE.Mesh
    Body1004_11: THREE.Mesh
    Body1004_12: THREE.Mesh
    Body24_1: THREE.Mesh
    Body24_2: THREE.Mesh
    Body24_3: THREE.Mesh
    Body24_4: THREE.Mesh
    Body24_5: THREE.Mesh
    Body24_6: THREE.Mesh
    Body24_7: THREE.Mesh
    Body24_8: THREE.Mesh
    Body24_9: THREE.Mesh
    Body24_10: THREE.Mesh
    Body24_11: THREE.Mesh
    Body24_12: THREE.Mesh
    Body24_13: THREE.Mesh
    Body24_14: THREE.Mesh
    Body24_15: THREE.Mesh
    Body24_16: THREE.Mesh
    Body24_17: THREE.Mesh
    Body24_18: THREE.Mesh
    ['49']: THREE.Mesh
    ['59']: THREE.Mesh
    Body1005: THREE.Mesh
    Body1005_1: THREE.Mesh
    Body1005_2: THREE.Mesh
    Body1005_3: THREE.Mesh
    Body1005_4: THREE.Mesh
    Body1005_5: THREE.Mesh
    Body1005_6: THREE.Mesh
  }
  materials: {
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    F_1b7ce1c36a944c75b371ca1f58ffc654: THREE.MeshStandardMaterial
    F_7d9c66a54911442dbd0ae8acc6103eaa: THREE.MeshStandardMaterial
    F_5c2d5c2a2d6449c09dade06ef277e335: THREE.MeshStandardMaterial
    F_c3768b6fcd444213803e766756bdec11: THREE.MeshStandardMaterial
    F_ae942cbb5a254932a7cc5c2138ab3ee0: THREE.MeshStandardMaterial
    F_9b96cefd0a1247bc9e339feb24ac22ff: THREE.MeshStandardMaterial
    F_adf06f622e2747bc9c3aef1ba1216e52: THREE.MeshStandardMaterial
    F_41a8b706e26f472a8bec2d609e636738: THREE.MeshStandardMaterial
    F_15717da78da64991aa8193e98595ec5c: THREE.MeshStandardMaterial
    F_3a9d47db4ac34a2a84c7cdbf9680dbc3: THREE.MeshStandardMaterial
    F_f319be99632b445ba72be29276ffb45e: THREE.MeshStandardMaterial
    F_47352e999f0449708b9f673287d86ea4: THREE.MeshStandardMaterial
    F_e1e4ef56068840c8be10c5ce4aab188c: THREE.MeshStandardMaterial
    F_d67c08e0af5b496f81cd06661001547d: THREE.MeshStandardMaterial
    F_b0c3005fff5b47bf985e660dacb5985d: THREE.MeshStandardMaterial
    F_7f41b6e8e27c4bc99810d76305f248bb: THREE.MeshStandardMaterial
    F_1c97abfee22049c89550d43f0627dc0b: THREE.MeshStandardMaterial
    F_a6deda6596ac401583b718ad9b87ce6c: THREE.MeshStandardMaterial
    F_4bd52a64377e46c2bf06159614a4d9a4: THREE.MeshStandardMaterial
    F_3b29331217e7431fb21ff33168c915f1: THREE.MeshStandardMaterial
    F_905b1c569bcf486981f4dff192ff78df: THREE.MeshStandardMaterial
    F_2b87062a5381469cac8d6938223bcfcd: THREE.MeshStandardMaterial
    F_c7931ca16e554fe0af426e9a03481be4: THREE.MeshStandardMaterial
    F_528dd34dcfbc4241b65cfc553a622e8f: THREE.MeshStandardMaterial
    F_f9e0c64ead2b41a0834f1732205657bb: THREE.MeshStandardMaterial
    F_600275ee008b43f39183522cb95f4404: THREE.MeshStandardMaterial
    ['F_698dbfa705734b12b40a79b486c99fa5.001']: THREE.MeshStandardMaterial
    ['F_6cd03d4ffc05424f858102a02f344a17.001']: THREE.MeshStandardMaterial
    ['F_821a1c8bf1234c9d979a7220508cba56.001']: THREE.MeshStandardMaterial
    ['F_b4a79d257dcd46e1a54dd53a1f9755e1.001']: THREE.MeshStandardMaterial
    ['F_7e3341f9adc647238df72a8962353f08.001']: THREE.MeshStandardMaterial
    ['F_4ee02fcf175149469d580b81652bf274.001']: THREE.MeshStandardMaterial
    ['F_34db09de63c94747b2e98353d1f61fbe.001']: THREE.MeshStandardMaterial
    ['F_c9af023199d34a4ebe0411ecc2b07c99.001']: THREE.MeshStandardMaterial
    ['F_348434d0f05046faa7f411ce24b04a22.001']: THREE.MeshStandardMaterial
    ['F_24255b602131456d9f27bfcb08f4d555.001']: THREE.MeshStandardMaterial
    ['F_961ea634f8b647f7935976be70efefc2.001']: THREE.MeshStandardMaterial
    F_6629540c523f4d8799b9dc88c2cac396: THREE.MeshStandardMaterial
    F_a1be3827db8b4986bacf523d90bf06cc: THREE.MeshStandardMaterial
    F_7b2d800f8c8d461588f43a1a5f939a28: THREE.MeshStandardMaterial
    F_a7c27df7b59c456c9f75ab6ed55d28d9: THREE.MeshStandardMaterial
    F_5b5e6ae247884fc8859b604a0c293a07: THREE.MeshStandardMaterial
    F_b9fe66f4cd09437a96cc095912862580: THREE.MeshStandardMaterial
    F_5fd5d2132d6a4eeda7c8efea16ad239c: THREE.MeshStandardMaterial
    F_29ca96d9dc0e470f8a51d5df3c4b19f5: THREE.MeshStandardMaterial
    F_8bccd581f061406dbea051452487685c_baked: THREE.MeshStandardMaterial
    F_5d624feedfb44980a0b2ae5e0013e3b4: THREE.MeshStandardMaterial
    F_e84b3e2d6516488cadcf33ed1ea13843: THREE.MeshStandardMaterial
    F_944c0a5388324ad986e65a2af541dc3e: THREE.MeshStandardMaterial
    F_d21c4a12cd3a46eca6f870b80341be2e: THREE.MeshStandardMaterial
    F_ed78eb61c8264069bc88d4e38b8775ea: THREE.MeshStandardMaterial
    F_0e26cfbb34e342c5ad2df9c8abc5d2bb: THREE.MeshStandardMaterial
    F_ec2c14429c2f4b7ebc537d2b9a86c1c8: THREE.MeshStandardMaterial
    F_49ffa6ca16104217805874d2413fca40: THREE.MeshStandardMaterial
    F_641f0f1d486d41159a4aa468dabdb147: THREE.MeshStandardMaterial
    F_7ec58926b06544bc9889dc9621cb312d: THREE.MeshStandardMaterial
    F_7155b5b10d6440bcbecca35d792953c6: THREE.MeshStandardMaterial
    F_09531f469fc04c9484751dd53e982e04: THREE.MeshStandardMaterial
    F_8a969adb58e0413db414914f46b386bc: THREE.MeshStandardMaterial
    F_ba4b0392a8fb40bd966eaf206fa25502: THREE.MeshStandardMaterial
    F_37a23d63f0f3460c991bf036760936f2: THREE.MeshStandardMaterial
    F_557283c95b694c329bed644c24d6e8cd: THREE.MeshStandardMaterial
    F_75ccba0141554822aed94d9bafd0642d: THREE.MeshStandardMaterial
    F_998e94b71450484da6e2936e63a772e7: THREE.MeshStandardMaterial
    F_cfde0b5d4bae4c44b1c52196ef852102: THREE.MeshStandardMaterial
    F_27e43f2f5bcf4202b187cf53c00742ac: THREE.MeshStandardMaterial
    F_743df6c4817d4978866b9b149311e599: THREE.MeshStandardMaterial
    F_743fe9b798cd4480bf60ec9e0c952d9e: THREE.MeshStandardMaterial
    F_612427862c6545b68ec7a2155e2df73c: THREE.MeshStandardMaterial
    F_d96a6a4413c64bf4b110c247b6f5f18d: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    F_1544a96fd3014cf6b98aa3fbd81c554e: THREE.MeshStandardMaterial
    F_548883c7a84a459a9977ee76ea294aac: THREE.MeshStandardMaterial
    F_7fd9a8d0304548d78505598f95341a7a: THREE.MeshStandardMaterial
    F_e76a45c66cea48d682702cda345d67e1: THREE.MeshStandardMaterial
    F_3722933669f04cc5b31fb0634b0e62f9: THREE.MeshStandardMaterial
    F_71eb9d48d6204a1d9e385cc7a7719764: THREE.MeshStandardMaterial
    F_053b8a8e2509437894d592df8c45637f: THREE.MeshStandardMaterial
    F_c52011ea7a1449d5b54a5fad1835b10b: THREE.MeshStandardMaterial
    F_447bd98df4d749159e1b71ae855360da: THREE.MeshStandardMaterial
    F_a306ce341cd646cd85f554a4a88b403b: THREE.MeshStandardMaterial
    F_9a760f0be54b413db1925935a84a6e2f: THREE.MeshStandardMaterial
    F_1bc16b9b09a948afac4e02310405610e: THREE.MeshStandardMaterial
    F_ba288b6f866a4ae48196c68a13de99ac: THREE.MeshStandardMaterial
    F_6060a1ccb61d42148067143ea32785c6: THREE.MeshStandardMaterial
    F_7286e19dd36a4b658e9a28a210d09acf: THREE.MeshStandardMaterial
    F_cada1d4a05ef49c29881d2aaa33eb53e: THREE.MeshStandardMaterial
    F_3109b1a5b5924ebbb45649c25117c77e: THREE.MeshStandardMaterial
    F_00c9a93c88444df69c7d50224408c9ed: THREE.MeshStandardMaterial
    F_04685a8a3f3746ca9df1f83acfbf6957: THREE.MeshStandardMaterial
    F_a477f637a7ff41fc8a6e690c1ef670e3: THREE.MeshStandardMaterial
    F_0ea195e2ab2642b78f1fa94a3596790f: THREE.MeshStandardMaterial
    F_a2010b4042e640968d3122683c4a2692: THREE.MeshStandardMaterial
    F_43239da84ce84e7a90d65a3b45622f7f: THREE.MeshStandardMaterial
    F_083dc01f2ae344e59d773d022e3b4ade: THREE.MeshStandardMaterial
    F_f75073ac70b14640a9db82843857e2ac: THREE.MeshStandardMaterial
    F_8295afca0fb04c6ab09b2c09abc273c2: THREE.MeshStandardMaterial
    F_55e1b39d3346429dbddbf897e6eab527: THREE.MeshStandardMaterial
    F_487d4b7875674024b9178bfe17b2d8c8: THREE.MeshStandardMaterial
    F_f2d777ee717f448d915e528887582dcb: THREE.MeshStandardMaterial
    F_49bfa08350e64e5daabc4ea973a56c1a: THREE.MeshStandardMaterial
    F_8a148073e2b247cc9687955ae6af9847: THREE.MeshStandardMaterial
  }
}


export function MDrew(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/MDrew/MDrew.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.005']} position={[0, 12.192, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.5, 6, 0.5]} />
      <mesh geometry={nodes.Circle.geometry} material={materials['Material.005']} position={[1.661, 12.196, -0.004]} rotation={[0, 0, -Math.PI / 2]} scale={1.2} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.003']} position={[0, 10.597, 3.815]} rotation={[-0.995, 0, 0]} scale={[1, 14.4, 1]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials['Material.005']} position={[-1.415, 13.41, 0.914]} rotation={[0, 0, -Math.PI / 2]} scale={[0.5, 6, 0.5]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.005']} position={[0, 8.605, 6.882]} rotation={[-0.995, 0, 0]} scale={[0.65, 22.836, 0.65]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials['Material.005']} position={[0, 13.101, 0.178]} rotation={[0, 0, -Math.PI / 2]} scale={[0.125, 0.99, 0.125]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials['Material.005']} position={[0, 13.311, 0.384]} rotation={[0, 0, -Math.PI / 2]} scale={[0.125, 0.99, 0.125]} />
      <group position={[0, 11.483, 1.576]} rotation={[-2.531, 0, -Math.PI]} scale={0.118}>
        <mesh geometry={nodes.Body1001_1.geometry} material={materials.F_1b7ce1c36a944c75b371ca1f58ffc654} />
        <mesh geometry={nodes.Body1001_2.geometry} material={materials.F_7d9c66a54911442dbd0ae8acc6103eaa} />
        <mesh geometry={nodes.Body1001_3.geometry} material={materials.F_5c2d5c2a2d6449c09dade06ef277e335} />
        <mesh geometry={nodes.Body1001_4.geometry} material={materials.F_c3768b6fcd444213803e766756bdec11} />
        <mesh geometry={nodes.Body1001_5.geometry} material={materials.F_ae942cbb5a254932a7cc5c2138ab3ee0} />
        <mesh geometry={nodes.Body1001_6.geometry} material={materials.F_9b96cefd0a1247bc9e339feb24ac22ff} />
        <mesh geometry={nodes.Body1001_7.geometry} material={materials.F_adf06f622e2747bc9c3aef1ba1216e52} />
        <mesh geometry={nodes.Body1001_8.geometry} material={materials.F_41a8b706e26f472a8bec2d609e636738} />
        <mesh geometry={nodes.Body1001_9.geometry} material={materials.F_15717da78da64991aa8193e98595ec5c} />
        <mesh geometry={nodes.Body1001_10.geometry} material={materials.F_3a9d47db4ac34a2a84c7cdbf9680dbc3} />
        <mesh geometry={nodes.Body1001_11.geometry} material={materials.F_f319be99632b445ba72be29276ffb45e} />
        <mesh geometry={nodes.Body1001_12.geometry} material={materials.F_47352e999f0449708b9f673287d86ea4} />
        <mesh geometry={nodes.Body1001_13.geometry} material={materials.F_e1e4ef56068840c8be10c5ce4aab188c} />
      </group>
      <group position={[0.732, 13.182, 1.362]} rotation={[0.576, -Math.PI / 2, 0]} scale={0.2}>
        <mesh geometry={nodes.Body1002.geometry} material={materials.F_d67c08e0af5b496f81cd06661001547d} />
        <mesh geometry={nodes.Body1002_1.geometry} material={materials.F_b0c3005fff5b47bf985e660dacb5985d} />
        <mesh geometry={nodes.Body1002_2.geometry} material={materials.F_7f41b6e8e27c4bc99810d76305f248bb} />
        <mesh geometry={nodes.Body1002_3.geometry} material={materials.F_1c97abfee22049c89550d43f0627dc0b} />
        <mesh geometry={nodes.Body1002_4.geometry} material={materials.F_a6deda6596ac401583b718ad9b87ce6c} />
        <mesh geometry={nodes.Body1002_5.geometry} material={materials.F_4bd52a64377e46c2bf06159614a4d9a4} />
      </group>
      <mesh geometry={nodes.Gear001.geometry} material={nodes.Gear001.material} position={[0.465, 13.41, 0.914]} rotation={[-Math.PI / 2, 0.017, -Math.PI / 2]} scale={4} />
      <mesh geometry={nodes.Gear004.geometry} material={nodes.Gear004.material} position={[0.729, 13.309, 1.158]} rotation={[-0.977, 0, 0]} scale={4} />
      <group position={[-0.518, 13.411, 0.914]} rotation={[-0.995, 0, -Math.PI / 2]} scale={0.2}>
        <mesh geometry={nodes.Body1018.geometry} material={materials.F_3b29331217e7431fb21ff33168c915f1} />
        <mesh geometry={nodes.Body1018_1.geometry} material={materials.F_905b1c569bcf486981f4dff192ff78df} />
        <mesh geometry={nodes.Body1018_2.geometry} material={materials.F_2b87062a5381469cac8d6938223bcfcd} />
        <mesh geometry={nodes.Body1018_3.geometry} material={materials.F_c7931ca16e554fe0af426e9a03481be4} />
        <mesh geometry={nodes.Body1018_4.geometry} material={materials.F_528dd34dcfbc4241b65cfc553a622e8f} />
        <mesh geometry={nodes.Body1018_5.geometry} material={materials.F_f9e0c64ead2b41a0834f1732205657bb} />
        <mesh geometry={nodes.Body1018_6.geometry} material={materials.F_600275ee008b43f39183522cb95f4404} />
      </group>
      <mesh geometry={nodes.Cylinder006.geometry} material={materials['Material.005']} position={[0, 13.381, 0.914]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.7, 1]} />
      <mesh geometry={nodes.Circle001.geometry} material={materials['Material.005']} position={[0.289, 12.196, -0.004]} rotation={[0, 0, -Math.PI / 2]} scale={[0.48, 1.2, 0.48]} />
      <mesh geometry={nodes.Circle002.geometry} material={materials['Material.005']} position={[-0.29, 12.196, -0.004]} rotation={[0, 0, -Math.PI / 2]} scale={[0.48, 1.2, 0.48]} />
      <mesh geometry={nodes.Circle003.geometry} material={materials['Material.005']} position={[-0.473, 12.196, -0.004]} rotation={[0, 0, -Math.PI / 2]} scale={1.2} />
      <mesh geometry={nodes.Circle004.geometry} material={materials['Material.005']} position={[-0.473, 10.672, -1.071]} rotation={[0, 0, -Math.PI / 2]} scale={0.6} />
      <group position={[0.305, 10.668, -1.067]} rotation={[0, 0, Math.PI / 2]} scale={0.1}>
        <mesh geometry={nodes.Body2005.geometry} material={materials['F_698dbfa705734b12b40a79b486c99fa5.001']} />
        <mesh geometry={nodes.Body2005_1.geometry} material={materials['F_6cd03d4ffc05424f858102a02f344a17.001']} />
        <mesh geometry={nodes.Body2005_2.geometry} material={materials['F_821a1c8bf1234c9d979a7220508cba56.001']} />
        <mesh geometry={nodes.Body2005_3.geometry} material={materials['F_b4a79d257dcd46e1a54dd53a1f9755e1.001']} />
        <mesh geometry={nodes.Body2005_4.geometry} material={materials['F_7e3341f9adc647238df72a8962353f08.001']} />
        <mesh geometry={nodes.Body2005_5.geometry} material={materials['F_4ee02fcf175149469d580b81652bf274.001']} />
        <mesh geometry={nodes.Body2005_6.geometry} material={materials['F_34db09de63c94747b2e98353d1f61fbe.001']} />
        <mesh geometry={nodes.Body2005_7.geometry} material={materials['F_c9af023199d34a4ebe0411ecc2b07c99.001']} />
        <mesh geometry={nodes.Body2005_8.geometry} material={materials['F_348434d0f05046faa7f411ce24b04a22.001']} />
        <mesh geometry={nodes.Body2005_9.geometry} material={materials['F_24255b602131456d9f27bfcb08f4d555.001']} />
        <mesh geometry={nodes.Body2005_10.geometry} material={materials['F_961ea634f8b647f7935976be70efefc2.001']} />
        <mesh geometry={nodes.Body2005_11.geometry} material={materials.F_6629540c523f4d8799b9dc88c2cac396} />
        <mesh geometry={nodes.Body2005_12.geometry} material={materials.F_a1be3827db8b4986bacf523d90bf06cc} />
        <mesh geometry={nodes.Body2005_13.geometry} material={materials.F_7b2d800f8c8d461588f43a1a5f939a28} />
        <mesh geometry={nodes.Body2005_14.geometry} material={materials.F_a7c27df7b59c456c9f75ab6ed55d28d9} />
      </group>
      <group position={[-0.027, -0.224, -0.086]} rotation={[Math.PI / 2, 0, 0]} scale={0.114}>
        <mesh geometry={nodes.Body1416_1.geometry} material={materials.F_5b5e6ae247884fc8859b604a0c293a07} />
        <mesh geometry={nodes.Body1416_2.geometry} material={materials.F_b9fe66f4cd09437a96cc095912862580} />
        <mesh geometry={nodes.Body1416_3.geometry} material={materials.F_5fd5d2132d6a4eeda7c8efea16ad239c} />
        <mesh geometry={nodes.Body1416_4.geometry} material={materials.F_29ca96d9dc0e470f8a51d5df3c4b19f5} />
        <mesh geometry={nodes.Body1416_5.geometry} material={materials.F_8bccd581f061406dbea051452487685c_baked} />
        <mesh geometry={nodes.Body1416_6.geometry} material={materials.F_5d624feedfb44980a0b2ae5e0013e3b4} />
        <mesh geometry={nodes.Body1416_7.geometry} material={materials.F_e84b3e2d6516488cadcf33ed1ea13843} />
        <mesh geometry={nodes.Body1416_8.geometry} material={materials.F_944c0a5388324ad986e65a2af541dc3e} />
        <mesh geometry={nodes.Body1416_9.geometry} material={materials.F_d21c4a12cd3a46eca6f870b80341be2e} />
        <mesh geometry={nodes.Body1416_10.geometry} material={materials.F_ed78eb61c8264069bc88d4e38b8775ea} />
        <mesh geometry={nodes.Body1416_11.geometry} material={materials.F_0e26cfbb34e342c5ad2df9c8abc5d2bb} />
        <mesh geometry={nodes.Body1416_12.geometry} material={materials.F_ec2c14429c2f4b7ebc537d2b9a86c1c8} />
        <mesh geometry={nodes.Body1416_13.geometry} material={materials.F_49ffa6ca16104217805874d2413fca40} />
        <mesh geometry={nodes.Body1416_14.geometry} material={materials.F_641f0f1d486d41159a4aa468dabdb147} />
        <mesh geometry={nodes.Body1416_15.geometry} material={materials.F_7ec58926b06544bc9889dc9621cb312d} />
        <mesh geometry={nodes.Body1416_16.geometry} material={materials.F_7155b5b10d6440bcbecca35d792953c6} />
        <mesh geometry={nodes.Body1416_17.geometry} material={materials.F_09531f469fc04c9484751dd53e982e04} />
        <mesh geometry={nodes.Body1416_18.geometry} material={materials.F_8a969adb58e0413db414914f46b386bc} />
        <mesh geometry={nodes.Body1416_19.geometry} material={materials.F_ba4b0392a8fb40bd966eaf206fa25502} />
        <mesh geometry={nodes.Body1416_20.geometry} material={materials.F_37a23d63f0f3460c991bf036760936f2} />
        <mesh geometry={nodes.Body1416_21.geometry} material={materials.F_557283c95b694c329bed644c24d6e8cd} />
        <mesh geometry={nodes.Body1416_22.geometry} material={materials.F_75ccba0141554822aed94d9bafd0642d} />
        <mesh geometry={nodes.Body1416_23.geometry} material={materials.F_998e94b71450484da6e2936e63a772e7} />
        <mesh geometry={nodes.Body1416_24.geometry} material={materials.F_cfde0b5d4bae4c44b1c52196ef852102} />
        <mesh geometry={nodes.Body1416_25.geometry} material={materials.F_27e43f2f5bcf4202b187cf53c00742ac} />
        <mesh geometry={nodes.Body1416_26.geometry} material={materials.F_743df6c4817d4978866b9b149311e599} />
        <mesh geometry={nodes.Body1416_27.geometry} material={materials.F_743fe9b798cd4480bf60ec9e0c952d9e} />
        <mesh geometry={nodes.Body1416_28.geometry} material={materials.F_612427862c6545b68ec7a2155e2df73c} />
        <mesh geometry={nodes.Body1416_29.geometry} material={materials.F_d96a6a4413c64bf4b110c247b6f5f18d} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} position={[-0.028, 0.015, -4.274]} scale={[30.363, 3.054, 1.012]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[-0.034, 0, -0.305]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 0.982, 1]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.001']} position={[4.877, -0.152, -2.743]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.5} />
      <mesh geometry={nodes.Text001.geometry} material={materials['Material.001']} position={[-4.943, -0.152, 2.438]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.5} />
      <mesh geometry={nodes.Text002.geometry} material={materials['Material.001']} position={[-3.048, -0.152, -4.42]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.5} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.005']} position={[0, 0, 0.762]} scale={[9, 1.5, 1]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.002']} position={[-1.372, 0, 0]} scale={[0.5, 1, 2]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.002']} position={[1.372, 0, 0]} scale={[0.5, 1, 2]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.002']} position={[0, 10.058, -1.067]} scale={[5, 1, 1.5]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.002']} position={[0, 7.62, 0.457]} scale={[4, 1, 1]} />
      <mesh geometry={nodes.Limelight_Vision_CAD.geometry} material={materials['Material.003']} position={[-1.981, 6.462, 0.914]} rotation={[-Math.PI, 0, 0]} scale={0.1} />
      <mesh geometry={nodes.Robot_Signal_Light_RSL_v1.geometry} material={materials['Material.004']} position={[-1.829, 10.058, 0.152]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.002']} position={[0, 6.248, -0.152]} scale={[4, 0.5, 1]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.002']} position={[0, 3.81, -0.152]} scale={[4, 0.5, 1]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.003']} position={[0.762, 5.029, -0.762]} scale={[1.2, 6, 1.2]} />
      <mesh geometry={nodes.Limelight_Vision_CAD001.geometry} material={materials['Material.003']} position={[1.829, 6.462, 0]} rotation={[-Math.PI, -1.571, 0]} scale={0.1} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.002']} position={[-1.829, 6.523, 0.914]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.006']} position={[1.798, 12.497, 0]} scale={[1, 1, 1.9]} />
      <mesh geometry={nodes.Text003.geometry} material={materials['Material.001']} position={[2.103, 10.058, 0.244]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials['Material.002']} position={[-1.829, 9.754, 0.152]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.003']} position={[1.829, 12.68, -0.457]} rotation={[0, 0, -Math.PI / 2]} scale={[0.25, 1, 0.25]} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.003']} position={[1.829, 12.68, 0.457]} rotation={[0, 0, -Math.PI / 2]} scale={[0.25, 1, 0.25]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.003']} position={[1.829, 7.437, 0.457]} rotation={[0, 0, -Math.PI / 2]} scale={[0.25, 1, 0.25]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials['Material.003']} position={[1.829, 7.437, -0.457]} rotation={[0, 0, -Math.PI / 2]} scale={[0.25, 1, 0.25]} />
      <group position={[-0.914, 10.058, -1.707]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={0.118}>
        <mesh geometry={nodes.Body1.geometry} material={materials.F_1b7ce1c36a944c75b371ca1f58ffc654} />
        <mesh geometry={nodes.Body1_1.geometry} material={materials.F_7d9c66a54911442dbd0ae8acc6103eaa} />
        <mesh geometry={nodes.Body1_2.geometry} material={materials.F_5c2d5c2a2d6449c09dade06ef277e335} />
        <mesh geometry={nodes.Body1_3.geometry} material={materials.F_c3768b6fcd444213803e766756bdec11} />
        <mesh geometry={nodes.Body1_4.geometry} material={materials.F_ae942cbb5a254932a7cc5c2138ab3ee0} />
        <mesh geometry={nodes.Body1_5.geometry} material={materials.F_9b96cefd0a1247bc9e339feb24ac22ff} />
        <mesh geometry={nodes.Body1_6.geometry} material={materials.F_adf06f622e2747bc9c3aef1ba1216e52} />
        <mesh geometry={nodes.Body1_7.geometry} material={materials.F_41a8b706e26f472a8bec2d609e636738} />
        <mesh geometry={nodes.Body1_8.geometry} material={materials.F_15717da78da64991aa8193e98595ec5c} />
        <mesh geometry={nodes.Body1_9.geometry} material={materials.F_3a9d47db4ac34a2a84c7cdbf9680dbc3} />
        <mesh geometry={nodes.Body1_10.geometry} material={materials.F_f319be99632b445ba72be29276ffb45e} />
        <mesh geometry={nodes.Body1_11.geometry} material={materials.F_47352e999f0449708b9f673287d86ea4} />
        <mesh geometry={nodes.Body1_12.geometry} material={materials.F_e1e4ef56068840c8be10c5ce4aab188c} />
      </group>
      <group position={[0, -0.213, -0.914]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.136}>
        <mesh geometry={nodes.Body1004.geometry} material={materials.F_1544a96fd3014cf6b98aa3fbd81c554e} />
        <mesh geometry={nodes.Body1004_1.geometry} material={materials.F_548883c7a84a459a9977ee76ea294aac} />
        <mesh geometry={nodes.Body1004_2.geometry} material={materials.F_7fd9a8d0304548d78505598f95341a7a} />
        <mesh geometry={nodes.Body1004_3.geometry} material={materials.F_e76a45c66cea48d682702cda345d67e1} />
        <mesh geometry={nodes.Body1004_4.geometry} material={materials.F_3722933669f04cc5b31fb0634b0e62f9} />
        <mesh geometry={nodes.Body1004_5.geometry} material={materials.F_71eb9d48d6204a1d9e385cc7a7719764} />
        <mesh geometry={nodes.Body1004_6.geometry} material={materials.F_053b8a8e2509437894d592df8c45637f} />
        <mesh geometry={nodes.Body1004_7.geometry} material={materials.F_c52011ea7a1449d5b54a5fad1835b10b} />
        <mesh geometry={nodes.Body1004_8.geometry} material={materials.F_447bd98df4d749159e1b71ae855360da} />
        <mesh geometry={nodes.Body1004_9.geometry} material={materials.F_a306ce341cd646cd85f554a4a88b403b} />
        <mesh geometry={nodes.Body1004_10.geometry} material={materials.F_9a760f0be54b413db1925935a84a6e2f} />
        <mesh geometry={nodes.Body1004_11.geometry} material={materials.F_1bc16b9b09a948afac4e02310405610e} />
        <mesh geometry={nodes.Body1004_12.geometry} material={materials.F_ba288b6f866a4ae48196c68a13de99ac} />
      </group>
      <group position={[2.743, -0.213, -0.61]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.189}>
        <mesh geometry={nodes.Body24_1.geometry} material={materials.F_6060a1ccb61d42148067143ea32785c6} />
        <mesh geometry={nodes.Body24_2.geometry} material={materials.F_7286e19dd36a4b658e9a28a210d09acf} />
        <mesh geometry={nodes.Body24_3.geometry} material={materials.F_cada1d4a05ef49c29881d2aaa33eb53e} />
        <mesh geometry={nodes.Body24_4.geometry} material={materials.F_3109b1a5b5924ebbb45649c25117c77e} />
        <mesh geometry={nodes.Body24_5.geometry} material={materials.F_00c9a93c88444df69c7d50224408c9ed} />
        <mesh geometry={nodes.Body24_6.geometry} material={materials.F_04685a8a3f3746ca9df1f83acfbf6957} />
        <mesh geometry={nodes.Body24_7.geometry} material={materials.F_a477f637a7ff41fc8a6e690c1ef670e3} />
        <mesh geometry={nodes.Body24_8.geometry} material={materials.F_0ea195e2ab2642b78f1fa94a3596790f} />
        <mesh geometry={nodes.Body24_9.geometry} material={materials.F_a2010b4042e640968d3122683c4a2692} />
        <mesh geometry={nodes.Body24_10.geometry} material={materials.F_43239da84ce84e7a90d65a3b45622f7f} />
        <mesh geometry={nodes.Body24_11.geometry} material={materials.F_083dc01f2ae344e59d773d022e3b4ade} />
        <mesh geometry={nodes.Body24_12.geometry} material={materials.F_f75073ac70b14640a9db82843857e2ac} />
        <mesh geometry={nodes.Body24_13.geometry} material={materials.F_8295afca0fb04c6ab09b2c09abc273c2} />
        <mesh geometry={nodes.Body24_14.geometry} material={materials.F_55e1b39d3346429dbddbf897e6eab527} />
        <mesh geometry={nodes.Body24_15.geometry} material={materials.F_487d4b7875674024b9178bfe17b2d8c8} />
        <mesh geometry={nodes.Body24_16.geometry} material={materials.F_f2d777ee717f448d915e528887582dcb} />
        <mesh geometry={nodes.Body24_17.geometry} material={materials.F_49bfa08350e64e5daabc4ea973a56c1a} />
        <mesh geometry={nodes.Body24_18.geometry} material={materials.F_8a148073e2b247cc9687955ae6af9847} />
      </group>
      <mesh geometry={nodes['49'].geometry} material={materials['Material.001']} position={[-3.51, -0.305, 4.267]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['59'].geometry} material={materials['Material.001']} position={[1.519, -0.305, 4.267]} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[-1.707, 12.192, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.2}>
        <mesh geometry={nodes.Body1005.geometry} material={materials.F_3b29331217e7431fb21ff33168c915f1} />
        <mesh geometry={nodes.Body1005_1.geometry} material={materials.F_905b1c569bcf486981f4dff192ff78df} />
        <mesh geometry={nodes.Body1005_2.geometry} material={materials.F_2b87062a5381469cac8d6938223bcfcd} />
        <mesh geometry={nodes.Body1005_3.geometry} material={materials.F_c7931ca16e554fe0af426e9a03481be4} />
        <mesh geometry={nodes.Body1005_4.geometry} material={materials.F_528dd34dcfbc4241b65cfc553a622e8f} />
        <mesh geometry={nodes.Body1005_5.geometry} material={materials.F_f9e0c64ead2b41a0834f1732205657bb} />
        <mesh geometry={nodes.Body1005_6.geometry} material={materials.F_600275ee008b43f39183522cb95f4404} />
      </group>
    </group>
  )
}

useGLTF.preload('/MDrew/MDrew.gltf')
